name: uberclone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

flutter_native_splash:
  background_image: assets/image/splash_image.png
  android_12:

dependencies:
  flutter_native_splash: ^2.1.6
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/image/


  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-VariableFont_wght.ttf
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Medium.ttf

    